import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";
type Dir = "ltr" | "rtl";

interface LanguageContextType {
  language: Language;
  dir: Dir;
  t: (key: string) => string;
  setLanguage: (lang: Language) => void;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    inbox: "Inbox",
    orders: "Orders",
    products: "Products",
    catalog_tools: "Catalog Tools",
    store_settings: "Store Settings",
    platforms: "Platforms",
    reports: "Reports",
    ai_settings: "AI Settings",
    growth: "Growth",
    notifications: "Notifications",
    menu: "Menu",
    search: "Search...",
    sign_out: "Sign out",
    store: "Store",
    active: "Active",
    pending: "Pending",
    suspended: "Suspended",
    no_store: "No store",
    add_product: "Add Product",
    edit_product: "Edit Product",
    save_changes: "Save Changes",
    cancel: "Cancel",
    delete: "Delete",
    create: "Create",
    update: "Update",
    saving: "Saving...",
    loading: "Loading...",
    select_conversation: "Select a conversation",
    no_conversations: "No conversations yet",
    no_messages: "No messages yet",
    type_reply: "Type a reply...",
    mark_resolved: "Mark Resolved",
    all: "All",
    connected: "Connected",
    not_connected: "Not Connected",
    messages: "Messages",
    last_synced: "Last Synced",
    connected_platforms: "Connected Platforms",
    manage_platforms: "Manage your messaging platform connections",
    store_information: "Store Information",
    business_hours: "Business Hours",
    delivery_information: "Delivery Information",
    return_policy: "Return Policy",
    no_products: "No products yet. Add your first product to get started.",
    low_stock: "Low Stock",
    out_of_stock: "Out of Stock",
    inactive: "Inactive",
    privacy_policy: "Privacy Policy",
    terms_of_use: "Terms of Use",
    disclaimer: "Disclaimer",
    // Dashboard
    welcome_back: "Welcome back",
    here_whats_happening: "Here's what's happening.",
    messages_today: "Messages Today",
    new_orders: "New Orders",
    pending_orders: "Pending Orders",
    revenue_month: "Revenue (Month)",
    orders_per_day: "Orders Per Day",
    recent_activity: "Recent Activity",
    no_activity_yet: "No activity yet. Start by adding products and connecting your messaging platforms.",
    // Orders
    total_orders: "total orders",
    export_csv: "Export CSV",
    create_order: "Create Order",
    order_id: "Order ID",
    customer: "Customer",
    phone_col: "Phone",
    total_col: "Total",
    status_col: "Status",
    platform_col: "Platform",
    date_col: "Date",
    no_orders: "No orders found.",
    update_status: "Update Status",
    customer_name_field: "Customer Name",
    address: "Address",
    notes: "Notes",
    creating: "Creating...",
    export: "Export",
    // Login / Signup
    welcome_back_login: "Welcome back",
    email: "Email",
    password: "Password",
    sign_in: "Sign In",
    continue_google: "Continue with Google",
    forgot_password: "Forgot password?",
    dont_have_account: "Don't have an account?",
    sign_up: "Sign up",
    already_have_account: "Already have an account?",
    log_in: "Log in",
    // Signup steps
    step_account: "Account",
    step_store_info: "Store Info",
    step_review: "Review",
    full_name: "Full Name",
    phone_number: "Phone Number",
    store_name: "Store Name",
    store_description: "Store Description",
    select_category: "Select Category",
    clothing_fashion: "Clothing & Fashion",
    electronics: "Electronics",
    food_beverage: "Food & Beverage",
    health_beauty: "Health & Beauty",
    upload_store_logo: "Upload Store Logo",
    store_address: "Store Address",
    review_details: "Review your details and submit. Your account will be reviewed by our team.",
    submit_review: "Submit for Review",
    name_field: "Name",
    account_created: "Account Created!",
    check_email: "Please check your email to verify your account. Your store will be reviewed by our team.",
    go_to_login: "Go to Login",
    back: "Back",
    next: "Next",
    // Store Settings
    manage_store_info: "Manage your store information",
    branding: "Branding",
    logo: "Logo",
    cover_image: "Cover Image",
    upload_cover: "Upload cover",
    store_name_field: "Store Name",
    category_field: "Category",
    description_field: "Description",
    phone_field: "Phone",
    email_field: "Email",
    address_field: "Address",
    to_label: "to",
    // Reports
    track_performance: "Track your store's performance",
    seven_days: "7 Days",
    thirty_days: "30 Days",
    ninety_days: "90 Days",
    conversations_label: "Conversations",
    conversion_rate: "Conversion Rate",
    avg_order_value: "Avg Order Value",
    by_platform: "By Platform",
    revenue_over_time: "Revenue Over Time",
    order_status_funnel: "Order Status Funnel",
    platform_performance: "Platform Performance",
    top_products: "Top Products",
    product_col: "Product",
    sold_col: "Sold",
    revenue_col: "Revenue",
    no_data_period: "No data for this period. Reports will populate as you receive orders and conversations.",
    conv_abbr: "conv.",
    convos_label: "convos",
    orders_label: "orders",
    revenue_label: "revenue",
    // Platforms
    not_connected_msg: "Not connected",
    pages_connected: "page(s) connected",
    add_pages: "Add Pages",
    connect: "Connect",
    webhook_url: "Webhook URL",
    setup_guide: "Setup Guide",
    loading_pages: "Loading pages...",
    select_pages_title: "Select Pages to Connect",
    select_pages_desc: "Choose which pages AI should manage. All selected pages will receive automatic replies.",
    select_all: "Select All",
    // Inbox
    past_orders: "Past Orders",
    no_orders_found: "No orders found",
    pending_order: "Pending Order",
    resolved_status: "Resolved",
    ai_on: "AI ON",
    ai_off: "AI OFF",
    // Notifications
    no_notifications: "No notifications yet",
    // DashboardLayout header
    or_divider: "or",
    last_updated: "Last updated: March 27, 2026",
    pp_s1_title: "1. Information We Collect",
    pp_s1_text: "We collect information you provide directly, such as your name, email address, phone number, and store details when you create an account. We also collect usage data, device information, and cookies automatically.",
    pp_s2_title: "2. How We Use Your Information",
    pp_s2_text: "We use your information to provide and improve our services, process orders, send notifications, respond to inquiries, and ensure platform security. We may also use aggregated data for analytics.",
    pp_s3_title: "3. Data Sharing",
    pp_s3_text: "We do not sell your personal data. We may share information with service providers who assist in operating our platform, or when required by law. Third-party integrations (Facebook, Instagram, WhatsApp) are governed by their own privacy policies.",
    pp_s4_title: "4. Data Security",
    pp_s4_text: "We implement industry-standard security measures to protect your data, including encryption, secure servers, and access controls. However, no method of transmission over the internet is 100% secure.",
    pp_s5_title: "5. Your Rights",
    pp_s5_text: "You have the right to access, update, or delete your personal information at any time. You may also opt out of marketing communications. Contact us to exercise these rights.",
    pp_s6_title: "6. Contact Us",
    pp_s6_text: "If you have questions about this Privacy Policy, please contact us through the platform's support channels.",
    tou_s1_title: "1. Acceptance of Terms",
    tou_s1_text: "By accessing or using our platform, you agree to be bound by these Terms of Use. If you do not agree, you may not use the service.",
    tou_s2_title: "2. Account Responsibilities",
    tou_s2_text: "You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized access. You must provide accurate and complete information when creating an account.",
    tou_s3_title: "3. Acceptable Use",
    tou_s3_text: "You agree not to use the platform for any unlawful purpose, to transmit harmful content, to interfere with the platform's operation, or to violate any applicable laws or regulations.",
    tou_s4_title: "4. Intellectual Property",
    tou_s4_text: "All content, features, and functionality of the platform are owned by us and are protected by copyright, trademark, and other intellectual property laws. You retain ownership of content you upload.",
    tou_s5_title: "5. Limitation of Liability",
    tou_s5_text: "To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the platform.",
    tou_s6_title: "6. Termination",
    tou_s6_text: "We reserve the right to suspend or terminate your access to the platform at our discretion, with or without notice, for conduct that violates these terms or is harmful to other users.",
    tou_s7_title: "7. Changes to Terms",
    tou_s7_text: "We may update these terms from time to time. Continued use of the platform after changes constitutes acceptance of the updated terms.",
    disc_s1_title: "1. General Information",
    disc_s1_text: "The information provided on this platform is for general informational purposes only. While we strive to keep the information accurate and up to date, we make no representations or warranties of any kind about the completeness, accuracy, or reliability of the information.",
    disc_s2_title: "2. AI-Generated Content",
    disc_s2_text: "Our platform uses artificial intelligence to assist with customer conversations, order processing, and recommendations. AI-generated responses may not always be accurate. Store owners are responsible for reviewing and confirming AI-assisted actions, including orders and customer communications.",
    disc_s3_title: "3. Third-Party Integrations",
    disc_s3_text: "Our platform integrates with third-party services such as Facebook, Instagram, and WhatsApp. We are not responsible for the content, privacy practices, or availability of these external services. Use of third-party services is subject to their respective terms and conditions.",
    disc_s4_title: "4. No Professional Advice",
    disc_s4_text: "Nothing on this platform constitutes professional, legal, financial, or business advice. You should consult with appropriate professionals before making business decisions based on information provided through our platform.",
    disc_s5_title: "5. Limitation of Responsibility",
    disc_s5_text: "We shall not be held responsible for any losses, damages, or issues arising from the use of our platform, including but not limited to order errors, miscommunications, or service interruptions.",
    // Products page extras
    products_count_suffix: "products",
    import_export: "Import / Export",
    import_csv: "Import CSV",
    export_csv_action: "Export CSV",
    csv_short: "CSV",
    add_short: "Add",
    edit: "Edit",
    duplicate: "Duplicate",
    confirm_delete_product: "Delete this product?",
    no_products_to_export: "No products to export",
    stock_label: "Stock",
    sku_label: "SKU",
    product_col_h: "Product",
    category_col_h: "Category",
    price_col_h: "Price",
    stock_col_h: "Stock",
    status_col_h: "Status",
    // Wizard
    edit_product_title: "Edit product",
    new_product_title: "New product",
    step_photos: "Photos",
    step_basics: "Basics",
    step_details: "Details",
    autofill_with_ai: "Autofill with AI",
    analyzing_image: "Analyzing image...",
    ai_suggestions_applied: "AI suggestions applied",
    ai_autofill_failed: "AI autofill failed",
    ai_hint: "✨ AI suggested — edit anytime in next steps",
    name_required: "Name is required",
    name_label: "Name",
    name_placeholder: "e.g. Classic Leather Wallet",
    price_label: "Price",
    compare_price_label: "Compare price",
    sku_optional: "optional",
    description_label: "Description",
    description_placeholder: "Tell customers what makes this product special...",
    category_label: "Category",
    active_visible: "Active (visible in storefront)",
    product_variations: "Product variations",
    sizes_placeholder: "Sizes (S, M, L)",
    colors_placeholder: "Colors (black, white)",
    stock_per_size_placeholder: "Stock per size (S: 4, M: 8)",
    sizes_label: "Sizes",
    colors_label: "Colors",
    stock_per_size_label: "Stock per size",
    custom_size_placeholder: "Custom size (e.g. XXL, 32)",
    custom_color_placeholder: "Custom color (e.g. Mint)",
    variations_optional_hint: "Optional — add sizes & colors",
    sizes_count_label: "sizes",
    colors_count_label: "colors",
    fill_all_with: "Fill all with",
    save_and_add_another: "Save & add another",
    save: "Save",
    // Category combobox
    select_category_placeholder: "Select category",
    search_or_create: "Search or create...",
    create_x: "Create",
    no_categories_yet: "No categories yet",
    // Image dropzone
    cover_badge: "Cover",
    uploading_n: "Uploading",
    drop_images_hint: "Drop images, paste, or click to browse",
    multiple_images_hint: "Multiple images supported · drag to reorder",
    // CSV dialog
    import_products_csv: "Import products from CSV",
    bulk_add_hint: "Bulk add many products at once",
    download_template: "Download template",
    click_to_upload_csv: "Click to upload CSV",
    csv_headers_hint: "Headers: name, description, category, price, compare_price, stock, sku, active, image_url",
    choose_different_file: "Choose different file",
    valid_label: "valid",
    invalid_label: "invalid",
    ok_label: "OK",
    importing_n_products: "Import",
    import_failed: "Import failed",
    imported_n_products: "Imported",
    products_imported_suffix: "products",
  },
  ar: {
    dashboard: "لوحة التحكم",
    inbox: "صندوق الوارد",
    orders: "الطلبات",
    products: "المنتجات",
    catalog_tools: "أدوات الكتالوج",
    store_settings: "إعدادات المتجر",
    platforms: "المنصات",
    reports: "التقارير",
    ai_settings: "إعدادات الذكاء الاصطناعي",
    growth: "النمو",
    notifications: "الإشعارات",
    menu: "القائمة",
    search: "بحث...",
    sign_out: "تسجيل الخروج",
    store: "المتجر",
    active: "نشط",
    pending: "قيد الانتظار",
    suspended: "معلق",
    no_store: "لا يوجد متجر",
    add_product: "إضافة منتج",
    edit_product: "تعديل المنتج",
    save_changes: "حفظ التغييرات",
    cancel: "إلغاء",
    delete: "حذف",
    create: "إنشاء",
    update: "تحديث",
    saving: "جاري الحفظ...",
    loading: "جاري التحميل...",
    select_conversation: "اختر محادثة",
    no_conversations: "لا توجد محادثات بعد",
    no_messages: "لا توجد رسائل بعد",
    type_reply: "اكتب ردك...",
    mark_resolved: "تم الحل",
    all: "الكل",
    connected: "متصل",
    not_connected: "غير متصل",
    messages: "الرسائل",
    last_synced: "آخر مزامنة",
    connected_platforms: "المنصات المتصلة",
    manage_platforms: "إدارة اتصالات منصات المراسلة",
    store_information: "معلومات المتجر",
    business_hours: "ساعات العمل",
    delivery_information: "معلومات التوصيل",
    return_policy: "سياسة الإرجاع",
    no_products: "لا توجد منتجات بعد. أضف أول منتج للبدء.",
    low_stock: "مخزون منخفض",
    out_of_stock: "نفذ المخزون",
    inactive: "غير نشط",
    privacy_policy: "سياسة الخصوصية",
    terms_of_use: "شروط الاستخدام",
    disclaimer: "إخلاء المسؤولية",
    // Dashboard
    welcome_back: "مرحباً بعودتك",
    here_whats_happening: "إليك ما يحدث.",
    messages_today: "رسائل اليوم",
    new_orders: "طلبات جديدة",
    pending_orders: "طلبات قيد الانتظار",
    revenue_month: "الإيرادات (الشهر)",
    orders_per_day: "الطلبات اليومية",
    recent_activity: "النشاط الأخير",
    no_activity_yet: "لا يوجد نشاط بعد. ابدأ بإضافة المنتجات وربط منصات المراسلة.",
    // Orders
    total_orders: "إجمالي الطلبات",
    export_csv: "تصدير CSV",
    create_order: "إنشاء طلب",
    order_id: "رقم الطلب",
    customer: "العميل",
    phone_col: "الهاتف",
    total_col: "الإجمالي",
    status_col: "الحالة",
    platform_col: "المنصة",
    date_col: "التاريخ",
    no_orders: "لا توجد طلبات.",
    update_status: "تحديث الحالة",
    customer_name_field: "اسم العميل",
    address: "العنوان",
    notes: "ملاحظات",
    creating: "جاري الإنشاء...",
    export: "تصدير",
    // Login / Signup
    welcome_back_login: "مرحباً بعودتك",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    sign_in: "تسجيل الدخول",
    continue_google: "المتابعة بـ Google",
    forgot_password: "نسيت كلمة المرور؟",
    dont_have_account: "ليس لديك حساب؟",
    sign_up: "إنشاء حساب",
    already_have_account: "لديك حساب بالفعل؟",
    log_in: "تسجيل الدخول",
    // Signup steps
    step_account: "الحساب",
    step_store_info: "معلومات المتجر",
    step_review: "المراجعة",
    full_name: "الاسم الكامل",
    phone_number: "رقم الهاتف",
    store_name: "اسم المتجر",
    store_description: "وصف المتجر",
    select_category: "اختر الفئة",
    clothing_fashion: "الملابس والأزياء",
    electronics: "الإلكترونيات",
    food_beverage: "الأغذية والمشروبات",
    health_beauty: "الصحة والجمال",
    upload_store_logo: "تحميل شعار المتجر",
    store_address: "عنوان المتجر",
    review_details: "راجع تفاصيلك وأرسل الطلب. سيتم مراجعة حسابك من قبل فريقنا.",
    submit_review: "إرسال للمراجعة",
    name_field: "الاسم",
    account_created: "تم إنشاء الحساب!",
    check_email: "يرجى التحقق من بريدك الإلكتروني لتفعيل حسابك. سيتم مراجعة متجرك من قبل فريقنا.",
    go_to_login: "الذهاب إلى تسجيل الدخول",
    back: "رجوع",
    next: "التالي",
    // Store Settings
    manage_store_info: "إدارة معلومات متجرك",
    branding: "الهوية البصرية",
    logo: "الشعار",
    cover_image: "صورة الغلاف",
    upload_cover: "تحميل الغلاف",
    store_name_field: "اسم المتجر",
    category_field: "الفئة",
    description_field: "الوصف",
    phone_field: "الهاتف",
    email_field: "البريد الإلكتروني",
    address_field: "العنوان",
    to_label: "إلى",
    // Reports
    track_performance: "تتبع أداء متجرك",
    seven_days: "7 أيام",
    thirty_days: "30 يوماً",
    ninety_days: "90 يوماً",
    conversations_label: "المحادثات",
    conversion_rate: "معدل التحويل",
    avg_order_value: "متوسط قيمة الطلب",
    by_platform: "حسب المنصة",
    revenue_over_time: "الإيرادات عبر الوقت",
    order_status_funnel: "مسار حالات الطلبات",
    platform_performance: "أداء المنصات",
    top_products: "أفضل المنتجات",
    product_col: "المنتج",
    sold_col: "المبيعات",
    revenue_col: "الإيرادات",
    no_data_period: "لا توجد بيانات لهذه الفترة. ستظهر التقارير عند استلام الطلبات والمحادثات.",
    conv_abbr: "% تحويل",
    convos_label: "محادثة",
    orders_label: "طلب",
    revenue_label: "إيراد",
    // Platforms
    not_connected_msg: "غير متصل",
    pages_connected: "صفحة متصلة",
    add_pages: "إضافة صفحات",
    connect: "اتصال",
    webhook_url: "رابط Webhook",
    setup_guide: "دليل الإعداد",
    loading_pages: "جاري تحميل الصفحات...",
    select_pages_title: "اختر الصفحات للاتصال",
    select_pages_desc: "اختر الصفحات التي سيديرها الذكاء الاصطناعي. جميع الصفحات المحددة ستتلقى ردوداً تلقائية.",
    select_all: "تحديد الكل",
    // Inbox
    past_orders: "الطلبات السابقة",
    no_orders_found: "لا توجد طلبات",
    pending_order: "طلب قيد الانتظار",
    resolved_status: "تم الحل",
    ai_on: "الذكاء اصطناعي ON",
    ai_off: "الذكاء اصطناعي OFF",
    // Notifications
    no_notifications: "لا توجد إشعارات بعد",
    // DashboardLayout header
    or_divider: "أو",
    last_updated: "آخر تحديث: 27 مارس 2026",
    pp_s1_title: "1. المعلومات التي نجمعها",
    pp_s1_text: "نجمع المعلومات التي تقدمها مباشرة، مثل اسمك وعنوان بريدك الإلكتروني ورقم هاتفك وتفاصيل متجرك عند إنشاء حساب. كما نجمع بيانات الاستخدام ومعلومات الجهاز وملفات تعريف الارتباط تلقائياً.",
    pp_s2_title: "2. كيف نستخدم معلوماتك",
    pp_s2_text: "نستخدم معلوماتك لتقديم خدماتنا وتحسينها، ومعالجة الطلبات، وإرسال الإشعارات، والرد على الاستفسارات، وضمان أمان المنصة. قد نستخدم أيضاً بيانات مجمعة للتحليلات.",
    pp_s3_title: "3. مشاركة البيانات",
    pp_s3_text: "نحن لا نبيع بياناتك الشخصية. قد نشارك المعلومات مع مزودي الخدمات الذين يساعدون في تشغيل منصتنا، أو عندما يتطلب القانون ذلك. تخضع عمليات التكامل مع الأطراف الثالثة (فيسبوك، إنستغرام، واتساب) لسياسات الخصوصية الخاصة بها.",
    pp_s4_title: "4. أمان البيانات",
    pp_s4_text: "نطبق إجراءات أمان وفقاً لمعايير الصناعة لحماية بياناتك، بما في ذلك التشفير والخوادم الآمنة وضوابط الوصول. ومع ذلك، لا توجد طريقة نقل عبر الإنترنت آمنة بنسبة 100%.",
    pp_s5_title: "5. حقوقك",
    pp_s5_text: "لديك الحق في الوصول إلى معلوماتك الشخصية أو تحديثها أو حذفها في أي وقت. يمكنك أيضاً إلغاء الاشتراك في الاتصالات التسويقية. تواصل معنا لممارسة هذه الحقوق.",
    pp_s6_title: "6. اتصل بنا",
    pp_s6_text: "إذا كانت لديك أسئلة حول سياسة الخصوصية هذه، يرجى التواصل معنا عبر قنوات دعم المنصة.",
    tou_s1_title: "1. قبول الشروط",
    tou_s1_text: "من خلال الوصول إلى منصتنا أو استخدامها، فإنك توافق على الالتزام بشروط الاستخدام هذه. إذا كنت لا توافق، فلا يجوز لك استخدام الخدمة.",
    tou_s2_title: "2. مسؤوليات الحساب",
    tou_s2_text: "أنت مسؤول عن الحفاظ على سرية بيانات اعتماد حسابك. توافق على إخطارنا فوراً بأي وصول غير مصرح به. يجب عليك تقديم معلومات دقيقة وكاملة عند إنشاء حساب.",
    tou_s3_title: "3. الاستخدام المقبول",
    tou_s3_text: "توافق على عدم استخدام المنصة لأي غرض غير قانوني، أو نقل محتوى ضار، أو التدخل في تشغيل المنصة، أو انتهاك أي قوانين أو لوائح سارية.",
    tou_s4_title: "4. الملكية الفكرية",
    tou_s4_text: "جميع المحتويات والميزات والوظائف الخاصة بالمنصة مملوكة لنا ومحمية بموجب قوانين حقوق النشر والعلامات التجارية وغيرها من قوانين الملكية الفكرية. تحتفظ بملكية المحتوى الذي تقوم بتحميله.",
    tou_s5_title: "5. تحديد المسؤولية",
    tou_s5_text: "إلى أقصى حد يسمح به القانون، لن نكون مسؤولين عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية ناشئة عن استخدامك للمنصة.",
    tou_s6_title: "6. الإنهاء",
    tou_s6_text: "نحتفظ بالحق في تعليق أو إنهاء وصولك إلى المنصة وفقاً لتقديرنا، مع أو بدون إشعار، بسبب سلوك ينتهك هذه الشروط أو يضر بالمستخدمين الآخرين.",
    tou_s7_title: "7. تغييرات على الشروط",
    tou_s7_text: "قد نقوم بتحديث هذه الشروط من وقت لآخر. يشكل استمرار استخدام المنصة بعد التغييرات قبولاً للشروط المحدثة.",
    disc_s1_title: "1. معلومات عامة",
    disc_s1_text: "المعلومات المقدمة على هذه المنصة هي لأغراض إعلامية عامة فقط. بينما نسعى للحفاظ على دقة المعلومات وتحديثها، لا نقدم أي تمثيلات أو ضمانات من أي نوع حول اكتمال المعلومات أو دقتها أو موثوقيتها.",
    disc_s2_title: "2. المحتوى المُنشأ بالذكاء الاصطناعي",
    disc_s2_text: "تستخدم منصتنا الذكاء الاصطناعي للمساعدة في محادثات العملاء ومعالجة الطلبات والتوصيات. قد لا تكون الردود المُنشأة بالذكاء الاصطناعي دقيقة دائماً. أصحاب المتاجر مسؤولون عن مراجعة وتأكيد الإجراءات المدعومة بالذكاء الاصطناعي، بما في ذلك الطلبات والتواصل مع العملاء.",
    disc_s3_title: "3. تكاملات الأطراف الثالثة",
    disc_s3_text: "تتكامل منصتنا مع خدمات أطراف ثالثة مثل فيسبوك وإنستغرام وواتساب. نحن غير مسؤولين عن المحتوى أو ممارسات الخصوصية أو توفر هذه الخدمات الخارجية. يخضع استخدام خدمات الأطراف الثالثة لشروطها وأحكامها الخاصة.",
    disc_s4_title: "4. ليست نصيحة مهنية",
    disc_s4_text: "لا يشكل أي شيء على هذه المنصة نصيحة مهنية أو قانونية أو مالية أو تجارية. يجب عليك استشارة المتخصصين المناسبين قبل اتخاذ قرارات تجارية بناءً على المعلومات المقدمة عبر منصتنا.",
    disc_s5_title: "5. تحديد المسؤولية",
    disc_s5_text: "لن نتحمل المسؤولية عن أي خسائر أو أضرار أو مشكلات ناشئة عن استخدام منصتنا، بما في ذلك على سبيل المثال لا الحصر أخطاء الطلبات أو سوء التواصل أو انقطاع الخدمة.",
    // Products page extras
    products_count_suffix: "منتج",
    import_export: "استيراد / تصدير",
    import_csv: "استيراد CSV",
    export_csv_action: "تصدير CSV",
    csv_short: "CSV",
    add_short: "إضافة",
    edit: "تعديل",
    duplicate: "نسخ",
    confirm_delete_product: "حذف هذا المنتج؟",
    no_products_to_export: "لا توجد منتجات للتصدير",
    stock_label: "المخزون",
    sku_label: "رمز المنتج",
    product_col_h: "المنتج",
    category_col_h: "الفئة",
    price_col_h: "السعر",
    stock_col_h: "المخزون",
    status_col_h: "الحالة",
    // Wizard
    edit_product_title: "تعديل المنتج",
    new_product_title: "منتج جديد",
    step_photos: "الصور",
    step_basics: "الأساسيات",
    step_details: "التفاصيل",
    autofill_with_ai: "تعبئة تلقائية بالذكاء الاصطناعي",
    analyzing_image: "جاري تحليل الصورة...",
    ai_suggestions_applied: "تم تطبيق اقتراحات الذكاء الاصطناعي",
    ai_autofill_failed: "فشل التعبئة التلقائية",
    ai_hint: "✨ اقتراحات الذكاء الاصطناعي — يمكنك تعديلها في الخطوات التالية",
    name_required: "الاسم مطلوب",
    name_label: "الاسم",
    name_placeholder: "مثال: محفظة جلدية كلاسيكية",
    price_label: "السعر",
    compare_price_label: "السعر المقارن",
    sku_optional: "اختياري",
    description_label: "الوصف",
    description_placeholder: "أخبر العملاء ما يميز هذا المنتج...",
    category_label: "الفئة",
    active_visible: "نشط (مرئي في المتجر)",
    product_variations: "خيارات المنتج",
    sizes_placeholder: "المقاسات (S, M, L)",
    colors_placeholder: "الألوان (أسود، أبيض)",
    stock_per_size_placeholder: "المخزون لكل مقاس (S: 4, M: 8)",
    sizes_label: "المقاسات",
    colors_label: "الألوان",
    stock_per_size_label: "المخزون لكل مقاس",
    custom_size_placeholder: "مقاس مخصص (مثل XXL أو 32)",
    custom_color_placeholder: "لون مخصص (مثل نعناعي)",
    variations_optional_hint: "اختياري — أضف المقاسات والألوان",
    sizes_count_label: "مقاس",
    colors_count_label: "لون",
    fill_all_with: "تعبئة الكل بـ",
    save_and_add_another: "حفظ وإضافة آخر",
    save: "حفظ",
    // Category combobox
    select_category_placeholder: "اختر فئة",
    search_or_create: "ابحث أو أنشئ...",
    create_x: "إنشاء",
    no_categories_yet: "لا توجد فئات بعد",
    // Image dropzone
    cover_badge: "غلاف",
    uploading_n: "جاري رفع",
    drop_images_hint: "أفلت الصور، الصق، أو اضغط للاختيار",
    multiple_images_hint: "يدعم صور متعددة · اسحب لإعادة الترتيب",
    // CSV dialog
    import_products_csv: "استيراد منتجات من CSV",
    bulk_add_hint: "أضف عدة منتجات دفعة واحدة",
    download_template: "تحميل القالب",
    click_to_upload_csv: "اضغط لرفع ملف CSV",
    csv_headers_hint: "العناوين: name, description, category, price, compare_price, stock, sku, active, image_url",
    choose_different_file: "اختر ملف آخر",
    valid_label: "صالح",
    invalid_label: "غير صالح",
    ok_label: "تمام",
    importing_n_products: "استيراد",
    import_failed: "فشل الاستيراد",
    imported_n_products: "تم استيراد",
    products_imported_suffix: "منتج",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("app-language") as Language) || "en";
  });

  const dir: Dir = language === "ar" ? "rtl" : "ltr";

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string) => translations[language][key] || key;

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, dir, t, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
